<?php
    $xtpl_body->parse('head');  
    $xtpl_body->parse('header.navi');
    $xtpl_body->parse('header');
    $xtpl_body->parse('body');
    $xtpl_body->parse('footer.navi');
    $xtpl_body->parse('footer');
    $xtpl_body->out('head');
    $xtpl_body->out('header');
    $xtpl_body->out('body');
    $xtpl_body->out('footer');
?>
